### ISSUE TITLE
Can't issue PR

### ISSUE THREAD

**Issue by datafunk** [Kamik423/NetNewsWire-Themes#1]
You write on https://nnw-themes.xyz/contributing/ that we should issue a PR for new themes, but I get a "permission denied". The repo is public, but I suspect PRs are limited to certain users. 
Here's what I'd like to submit, if that helps: https://github.com/datafunk/NNW-newsjunkie-theme

**Comment by Kamik423** [comment]
For creating a PR you need to first fork the repository, add your changes to the forked repo and then create a pull request to pull the fork into the main repo. Did you do that?

**Comment by datafunk** [comment]
Thanks for your reply,

Yes, here are the steps I've taken - pretty standard I thought:
```bash
$ git clone git@github.com:Kamik423/nnw-themes.xyz.git
$ git checkout -b <mybranch>
# ... make my changes
$ git push origin <mybranch>
# ... computer says 'no'...
ERROR: Permission to Kamik423/nnw-themes.xyz.git denied to datafunk.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I did a bit of googling and GH says I should be doing `gh fork ....`, - I guess I could do that if that's the only way. Pretty silly from GitHub, though, must be a Microsoft thingie as `fork` is not an actual `git` command. Let me know if that's what I should be doing and I'll install `gh`.

While I have you and taking your time, do you want me to get `publish` and run that as well before submitting my PR? Any gotyas there or I just run it n the project root and that's that?

**Comment by Kamik423** [comment]
You want to fork https://github.com/Kamik423/nnw-themes.xyz to a repo of your own user https://github.com/datafunk/nnw-themes.xyz — you can delete this after the PR as accepted.

**Comment by datafunk** [comment]
Thanks, all makes sense now. The process happens in the web ui for the most part. Live and learn. Thanks for your help.
