### ISSUE TITLE
Theme creation

### ISSUE THREAD

**Issue by vada-pav** [Kamik423/NetNewsWire-Themes#4]
Hello,

I was wondering if you could help me create my theme. The documentation is hard for me to understand.

Thanks.

**Comment by Kamik423** [comment]
If you have some experience with HTML/CSS it would be best to start by looking at one theme and modifying it. This one is the best documented: https://github.com/stuartbreckenridge/NNWThemesPromenade

For questions you should probably join the slack: https://netnewswire.com/slack

**Comment by vada-pav** [comment]
I have modified a theme but i am not sure how to install it on my app and try it out. Thanks for the help though.

**Comment by Kamik423** [comment]
Are you on iOS or macOS?

**Comment by vada-pav** [comment]
MacOS. I figured it out. Now I am trying to change colors and see for myself.
Just curious, is there a simpler way?
This is what I am doing currently,
-change the color in the file
-commit changes
-download the zip file again
-install the theme

**Comment by Kamik423** [comment]
There is no reason to commit changes. When you have the .nnwtheme “file” you can double-click it and it will install.

Once it is installed you can just edit it in `Preferences>General>Open Theme Folder` and NNW will live-reload.

**Comment by vada-pav** [comment]
![Screenshot 2022-04-26 at 11 24 06 AM](https://user-images.githubusercontent.com/59252456/165233833-fdc7eb8b-7d3b-42e6-beea-16e7b021af82.png)

This is what I created.

**Comment by Kamik423** [comment]
Nice! If you feel confident enough you can add it as a pull request!

**Comment by vada-pav** [comment]
I am facing an issue now. Every time I make changes to css file on my machine and save it, and then install the theme again, it gives me an error.

![Screenshot 2022-04-27 at 12 35 10 AM](https://user-images.githubusercontent.com/59252456/165373793-ee1f1eed-99d5-4ea7-9e77-735f1d3237a1.png)

Am I doing something wrong?

Here are the steps I am taking.
-cloned the NewsJunkie theme on my machine
-Installed the theme
-Opened the theme folder from Preferences
-Duplicated the Theme
-renamed it
-Show Package Contents
-Opened the stylesheet.css file in VS Code
-Made changes
-saved the file
-Double clicked the .nnwtheme file again
-thats when i get the error that the file does not exist

Could you please help me out here?

**Comment by Kamik423** [comment]
I am not the NNW developer. But I don’t think you should duplicate it _inside_ the themes folder. Try to copy it to your desktop to install from there.

You don’t need to reinstall themes when you change them inside the themes folder, NNW will reload automatically if I remember correctly.

**Comment by vada-pav** [comment]
Thanks, I will try that out.
